## DATA PREPROCESSING AND DATA CLEANING

In [1]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('heart_risk.csv')

df.head()

,Age,Gender,BMI,Smoking_Status,COVID_Severity,SpO2,Blood_Pressure,Heart_Rate,ECG_Result,Troponin_Level,D_Dimer,CRP,Blood_Sugar,Cholesterol_Level,Hypertension,Diabetes,Vaccine_Given,Heart_Risk
0,69,Male,29.0,Yes,Severe,92.9,127,121,Abnormal,59.77,1.23,75.53,247,155,No,Yes,Yes,High Risk
1,32,Male,18.3,Yes,Severe,96.3,168,62,Abnormal,94.83,4.30,52.56,190,266,No,No,Yes,Medium Risk
2,89,Female,37.9,No,Moderate,89.2,121,87,Normal,28.25,1.76,120.99,180,176,Yes,No,Yes,High Risk
3,78,Male,19.0,No,Moderate,85.8,141,85,Normal,24.74,4.45,156.48,235,226,Yes,No,Yes,High Risk
4,38,Female,25.1,Yes,Moderate,92.3,90,86,Abnormal,2.64,1.70,21.93,227,158,Yes,No,Yes,Low Risk

In [3]:
df.tail()

,Age,Gender,BMI,Smoking_Status,COVID_Severity,SpO2,Blood_Pressure,Heart_Rate,ECG_Result,Troponin_Level,D_Dimer,CRP,Blood_Sugar,Cholesterol_Level,Hypertension,Diabetes,Vaccine_Given,Heart_Risk
9995,88,Female,35.8,Yes,Moderate,88.7,172,115,Normal,39.24,4.51,104.86,103,185,No,Yes,Yes,High Risk
9996,43,Male,35.8,No,Moderate,96.2,114,91,Normal,11.79,2.58,55.51,198,155,Yes,Yes,Yes,Low Risk
9997,63,Male,26.1,No,Moderate,90.3,128,80,Abnormal,59.31,0.88,93.98,245,236,Yes,No,Yes,High Risk
9998,63,Female,30.5,Yes,Moderate,86.3,157,55,Abnormal,21.39,1.17,19.99,213,138,Yes,Yes,No,High Risk
9999,31,Male,35.5,Yes,Moderate,94.4,135,68,Abnormal,44.45,3.70,35.42,174,263,No,No,No,Medium Risk

In [4]:
df.shape

(10000, 18)

In [5]:
df.size

180000

In [6]:
df.columns

Index(['Age', 'Gender', 'BMI', 'Smoking_Status', 'COVID_Severity', 'SpO2',
       'Blood_Pressure', 'Heart_Rate', 'ECG_Result', 'Troponin_Level',
       'D_Dimer', 'CRP', 'Blood_Sugar', 'Cholesterol_Level', 'Hypertension',
       'Diabetes', 'Vaccine_Given', 'Heart_Risk'],
      dtype='object')

In [7]:
df.isnull()

,Age,Gender,BMI,Smoking_Status,COVID_Severity,SpO2,Blood_Pressure,Heart_Rate,ECG_Result,Troponin_Level,D_Dimer,CRP,Blood_Sugar,Cholesterol_Level,Hypertension,Diabetes,Vaccine_Given,Heart_Risk
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [8]:
df = df.dropna()

In [9]:
df['COVID_Severity'].value_counts()

COVID_Severity
Moderate    3443
Severe      3334
Mild        3223
Name: count, dtype: int64

In [10]:
df.describe()

,Age,BMI,SpO2,Blood_Pressure,Heart_Rate,Troponin_Level,D_Dimer,CRP,Blood_Sugar,Cholesterol_Level
count,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,53.539700,28.96025,92.514300,134.691200,94.427700,50.074300,2.566828,99.194864,160.162900,208.165700
std,20.757324,6.33044,4.337211,26.033191,26.248982,28.612141,1.410529,58.165120,51.713265,51.857564
min,18.000000,18.00000,85.000000,90.000000,50.000000,0.030000,0.100000,0.120000,70.000000,120.000000
25%,36.000000,23.50000,88.800000,112.000000,72.000000,25.377500,1.340000,47.880000,115.000000,163.000000
50%,53.000000,28.90000,92.500000,135.000000,94.000000,49.945000,2.600000,99.460000,160.000000,207.000000
75%,72.000000,34.40000,96.300000,157.000000,118.000000,75.165000,3.780000,149.802500,205.000000,253.000000
max,89.000000,40.00000,100.000000,179.000000,139.000000,99.990000,5.000000,200.000000,249.000000,299.000000

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                10000 non-null  int64
 1   Gender             10000 non-null  object
 2   BMI                10000 non-null  float64
 3   Smoking_Status     10000 non-null  object
 4   COVID_Severity     10000 non-null  object
 5   SpO2               10000 non-null  float64
 6   Blood_Pressure     10000 non-null  int64
 7   Heart_Rate         10000 non-null  int64
 8   ECG_Result         10000 non-null  object
 9   Troponin_Level     10000 non-null  float64
 10  D_Dimer            10000 non-null  float64
 11  CRP                10000 non-null  float64
 12  Blood_Sugar        10000 non-null  int64
 13  Cholesterol_Level  10000 non-null  int64
 14  Hypertension       10000 non-null  object
 15  Diabetes           10000 non-null  object
 16  Vaccine_Given      10000 non-null  object
 17  Heart_Risk         10000 non-null  object
dtypes: float64(5), int64(5), object(8)
memory usage: 1.4+ MB

In [12]:
df['Heart_Risk'].unique()

array(['High Risk', 'Medium Risk', 'Low Risk'], dtype=object)

In [13]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
k=['Gender','Smoking_Status','COVID_Severity','ECG_Result','Hypertension','Diabetes','Heart_Risk','Vaccine_Given']

for i in k:
    df[i] = le.fit_transform(df[i]).astype(int)

In [14]:
df['Heart_Risk'].value_counts()

Heart_Risk
2    5617
0    3413
1     970
Name: count, dtype: int64

In [15]:
df.corr()

,Age,Gender,BMI,Smoking_Status,COVID_Severity,SpO2,Blood_Pressure,Heart_Rate,ECG_Result,Troponin_Level,D_Dimer,CRP,Blood_Sugar,Cholesterol_Level,Hypertension,Diabetes,Vaccine_Given,Heart_Risk
Age,1.000000,-0.003312,-0.012772,-0.008413,3.124460e-03,0.008674,0.004889,-0.001755,-0.010581,0.016304,0.013885,-0.004364,0.000683,0.004384,0.002904,0.005937,4.926066e-03,-0.335934
Gender,-0.003312,1.000000,0.011362,0.016210,6.743932e-03,-0.001973,0.004355,0.009635,-0.010905,0.000616,-0.017610,0.017851,0.003351,0.005683,-0.010372,0.000991,5.530397e-03,0.012306
BMI,-0.012772,0.011362,1.000000,0.008909,5.660534e-04,-0.002169,-0.015646,-0.007154,0.013381,0.003005,0.010813,0.012275,-0.004572,0.008345,0.007128,-0.014084,1.281666e-02,0.009824
Smoking_Status,-0.008413,0.016210,0.008909,1.000000,-1.668154e-02,0.000745,-0.003181,0.008909,-0.023796,0.011622,-0.001092,-0.004456,-0.019300,0.014371,-0.001593,0.012000,-1.040582e-02,-0.002307
COVID_Severity,0.003124,0.006744,0.000566,-0.016682,1.000000e+00,0.002469,-0.002997,0.012161,-0.003236,0.003844,0.009137,0.010420,0.010676,-0.005460,-0.000950,-0.014195,1.235110e-07,0.017308
SpO2,0.008674,-0.001973,-0.002169,0.000745,2.469347e-03,1.000000,-0.007945,-0.009301,-0.010343,-0.003364,0.014466,0.010812,-0.010130,-0.009141,-0.014585,-0.002544,-1.669166e-02,0.289166
Blood_Pressure,0.004889,0.004355,-0.015646,-0.003181,-2.997156e-03,-0.007945,1.000000,0.017984,-0.000700,-0.005714,0.001466,-0.003369,-0.002289,-0.002328,0.010601,0.017026,-1.665028e-02,-0.010578
Heart_Rate,-0.001755,0.009635,-0.007154,0.008909,1.216125e-02,-0.009301,0.017984,1.000000,0.004533,-0.016398,0.013238,0.000038,0.018011,-0.005729,0.001713,-0.004634,4.848272e-03,-0.001437
ECG_Result,-0.010581,-0.010905,0.013381,-0.023796,-3.236041e-03,-0.010343,-0.000700,0.004533,1.000000,-0.030496,0.010666,-0.003787,-0.017438,0.013918,-0.003485,-0.009805,1.026548e-02,0.199266
Troponin_Level,0.016304,0.000616,0.003005,0.011622,3.844360e-03,-0.003364,-0.005714,-0.016398,-0.030496,1.000000,-0.014321,0.001781,0.019697,0.006225,-0.016841,-0.013510,-3.293190e-03,-0.245308
D_Dimer,0.013885,-0.017610,0.010813,-0.001092,9.136660e-03,0.014466,0.001466,0.013238,0.010666,-0.014321,1.000000,-0.000146,0.011905,0.007009,-0.012107,0.013428,-9.574192e-03,0.008094
CRP,-0.004364,0.017851,0.012275,-0.004456,1.042036e-02,0.010812,-0.003369,0.000038,-0.003787,0.001781,-0.000146,1.000000,0.005098,-0.006823,0.000505,0.018975,-5.511942e-03,-0.007909
Blood_Sugar,0.000683,0.003351,-0.004572,-0.019300,1.067597e-02,-0.010130,-0.002289,0.018011,-0.017438,0.019697,0.011905,0.005098,1.000000,0.001847,0.008777,-0.004866,7.728579e-03,-0.012377
Cholesterol_Level,0.004384,0.005683,0.008345,0.014371,-5.459927e-03,-0.009141,-0.002328,-0.005729,0.013918,0.006225,0.007009,-0.006823,0.001847,1.000000,-0.015142,-0.003491,-2.769206e-03,0.003588
Hypertension,0.002904,-0.010372,0.007128,-0.001593,-9.498523e-04,-0.014585,0.010601,0.001713,-0.003485,-0.016841,-0.012107,0.000505,0.008777,-0.015142,1.000000,0.012794,4.506696e-03,-0.200586
Diabetes,0.005937,0.000991,-0.014084,0.012000,-1.419497e-02,-0.002544,0.017026,-0.004634,-0.009805,-0.013510,0.013428,0.018975,-0.004866,-0.003491,0.012794,1.000000,-4.394779e-03,-0.197185
Vaccine_Given,0.004926,0.005530,0.012817,-0.010406,1.235110e-07,-0.016692,-0.016650,0.004848,0.010265,-0.003293,-0.009574,-0.005512,0.007729,-0.002769,0.004507,-0.004395,1.000000e+00,-0.004310
Heart_Risk,-0.335934,0.012306,0.009824,-0.002307,1.730775e-02,0.289166,-0.010578,-0.001437,0.199266,-0.245308,0.008094,-0.007909,-0.012377,0.003588,-0.200586,-0.197185,-4.309795e-03,1.000000

In [16]:
pd.Categorical(df["Heart_Risk"]).describe()

            counts   freqs
categories
0             3413  0.3413
1              970  0.0970
2             5617  0.5617

In [17]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [18]:
df = df.drop_duplicates()

In [19]:
sum(df.duplicated())

0